# Task-specific config for DAgger / E2 data collection on RoboMimic transport MH.
task: transport_mh
dataset_path: data/robomimic/datasets/transport/mh/low_dim_abs.hdf5

recording:
  obs_keys:
    - object
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - robot1_eef_pos
    - robot1_eef_quat
    - robot1_gripper_qpos

pygame:
  spatial_mapping:
    left_stick_xy_mix:
      - [0.0, -1.0]
      - [1.0, 0.0]
  rotation_mapping:
    yaw_source: trigger_diff
    pitch_source: right_stick_x
