"""Layer 2 — slice and rollout access tools.

Surfaces the underlying rollouts and slices behind the graph. Tools split into
two cost classes:

* **Cheap (textual)**: ``list_slices_in_node``, ``get_rollout_summary``,
  ``list_rollouts``. Return only structured data.
* **Visual / video**: ``get_slice_video``, ``get_rollout_video``. Return
  PIL images (storyboard) or paths to MP4s (video). Counted against the
  budget; cached so a re-fetched slice charges nothing on the second call.

Slice IDs follow the form ``"{rollout_id}_t{start_frame}_t{end_frame}"``,
e.g. ``"r0023_t12_t30"``. The id is generated by the ``list_slices_in_node``
response and parsed by the ``get_slice_*`` tools.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from PIL import Image

from policy_doctor.vlm.proposals.agents.context import SessionContext
from policy_doctor.vlm.proposals.agents.tools import schema as S
from policy_doctor.vlm.proposals.agents.tools.types import (
    ImageBlock,
    TextBlock,
    ToolResult,
    ToolSpec,
)
from policy_doctor.vlm.proposals.pool import (
    episode_idx_to_rollout_id,
    rollout_id_to_episode_idx,
)


_SLICE_ID_RE = re.compile(r"^(r\d+)_t(\d+)_t(\d+)$")


# ---------------------------------------------------------------------------
# Slice id helpers
# ---------------------------------------------------------------------------


def slice_id(rollout_id: str, start: int, end: int) -> str:
    return f"{rollout_id}_t{int(start)}_t{int(end)}"


def parse_slice_id(slice_id_str: str) -> Optional[Tuple[str, int, int]]:
    m = _SLICE_ID_RE.match(slice_id_str.strip())
    if not m:
        return None
    return m.group(1), int(m.group(2)), int(m.group(3))


def _slice_bounds(meta: Dict[str, Any]) -> Tuple[int, int]:
    start = int(meta.get("window_start", meta.get("timestep", 0)))
    end = meta.get("window_end")
    if end is None:
        end = start + int(meta.get("window_width", 1)) - 1
    else:
        end = int(end) - 1
    return start, end


# ---------------------------------------------------------------------------
# list_slices_in_node
# ---------------------------------------------------------------------------


def _make_list_slices_in_node(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        node_id = int(args.get("node_id"))
        n = int(args.get("n", 20))
        sort_by = str(args.get("sort_by", "centroid_distance"))
        if node_id >= 0:
            ctx.inspected_nodes.add(int(node_id))

        if ctx.cluster_labels is None or ctx.cluster_metadata is None:
            return ToolResult.error(
                "list_slices_in_node",
                "no cluster_labels/metadata available on session context",
                code="not_available",
            )

        labels = np.asarray(ctx.cluster_labels)
        members = [
            (i, ctx.cluster_metadata[i])
            for i in range(len(labels))
            if int(labels[i]) == node_id
        ]
        if not members:
            return ToolResult.text(
                "list_slices_in_node",
                json.dumps({"node_id": node_id, "n_slices": 0, "slices": []}),
            )

        # Outcome and rollout-id annotations from metadata.
        outcomes = {True: "success", False: "failure", None: "unknown"}
        rows: List[Dict[str, Any]] = []
        for slice_idx, meta in members:
            ep_idx = int(meta.get("rollout_idx", meta.get("demo_idx", -1)))
            if ep_idx < 0:
                continue
            rid = episode_idx_to_rollout_id(ep_idx)
            start, end = _slice_bounds(meta)
            rows.append({
                "slice_idx": slice_idx,
                "slice_id": slice_id(rid, start, end),
                "rollout_id": rid,
                "start_frame": start,
                "end_frame": end,
                "outcome": outcomes.get(meta.get("success")),
                # Centroid distance filled in below if available.
                "centroid_distance": None,
            })

        # Centroid-distance sort if centroids + per-slice embeddings are available.
        if sort_by == "centroid_distance" and ctx.cluster_centroids is not None:
            try:
                _populate_centroid_distance(ctx, rows)
                rows.sort(key=lambda r: (r["centroid_distance"] is None, r["centroid_distance"] or 0.0))
            except Exception:
                # Non-fatal — return unsorted with a note.
                pass
        else:
            # Stable random shuffle seeded by node_id for reproducibility.
            rng = np.random.default_rng(seed=int(node_id))
            indices = list(range(len(rows)))
            rng.shuffle(indices)
            rows = [rows[i] for i in indices]

        return ToolResult.text(
            "list_slices_in_node",
            json.dumps(
                {"node_id": node_id, "n_slices": len(rows), "slices": rows[:n]},
                default=str,
            ),
        )

    return ToolSpec(
        name="list_slices_in_node",
        description=(
            "List slices assigned to a behavior cluster, with rollout id, frame range, "
            "and outcome. Use sort_by='centroid_distance' (default) for the most "
            "prototypical examples first."
        ),
        input_schema=S.LIST_SLICES_IN_NODE,
        func=_run,
        cost="cheap",
        # Specific cluster lookup. Charges normally; remains callable after
        # exhaustion as a recovery affordance for the cluster_not_inspected gate.
        bypass_when_exhausted=True,
    )


def _populate_centroid_distance(ctx: SessionContext, rows: List[Dict[str, Any]]) -> None:
    """Fill ``centroid_distance`` for each row, when per-slice coords are stashed in metadata.

    Most clustering pipelines record post-UMAP coordinates in ``metadata[i]['coords']``
    or ``metadata[i]['embedding']``. We try a few common keys and fall back to
    leaving the distance as None when none are present.
    """
    centroids = np.asarray(ctx.cluster_centroids)
    for row in rows:
        meta = ctx.cluster_metadata[row["slice_idx"]]
        coords = meta.get("coords") or meta.get("embedding") or meta.get("reduced_coords")
        if coords is None:
            continue
        c = np.asarray(coords, dtype=float)
        # Distance to *this* row's assigned cluster centroid.
        labels = np.asarray(ctx.cluster_labels)
        node_id = int(labels[row["slice_idx"]])
        if 0 <= node_id < len(centroids):
            d = float(np.linalg.norm(c - centroids[node_id]))
            row["centroid_distance"] = round(d, 4)


# ---------------------------------------------------------------------------
# get_rollout_summary  (graph-aware variant; A_NG version is in no_graph.py)
# ---------------------------------------------------------------------------


def _make_get_rollout_summary(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        rid = str(args.get("rollout_id", ""))
        try:
            entry = ctx.pool.by_id(rid)
        except KeyError:
            return ToolResult.error(
                "get_rollout_summary",
                f"rollout_id={rid!r} not in pool",
                code="not_found",
            )

        outcome = (
            "success" if entry.success is True
            else ("failure" if entry.success is False else "unknown")
        )
        cluster_path_named = None
        if entry.cluster_path:
            from policy_doctor.vlm.proposals.agents.tools.topology import _node_name

            cluster_path_named = [_node_name(c) for c in entry.cluster_path]

        payload = {
            "rollout_id": entry.rollout_id,
            "outcome": outcome,
            "length": entry.length,
            "cluster_path_ids": entry.cluster_path,
            "cluster_path": cluster_path_named,
            "has_storyboard": entry.storyboard_path is not None and entry.storyboard_path.exists(),
            "has_video": entry.video_path is not None and entry.video_path.exists(),
        }
        return ToolResult.text("get_rollout_summary", json.dumps(payload, default=str))

    return ToolSpec(
        name="get_rollout_summary",
        description=(
            "Cluster path and metadata for one rollout (no images). The cluster_path "
            "is the run-length-collapsed sequence of behavior cluster ids the rollout "
            "traversed, ending in SUCCESS / FAILURE / END."
        ),
        input_schema=S.GET_ROLLOUT_SUMMARY,
        func=_run,
        cost="cheap",
        # Specific rollout lookup. Charges normally; remains callable after
        # exhaustion so the agent can verify reference_rollout_id pre-submit.
        bypass_when_exhausted=True,
    )


# ---------------------------------------------------------------------------
# list_rollouts
# ---------------------------------------------------------------------------


def _make_list_rollouts(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        outcome = args.get("outcome")
        passes_through = list(args.get("passes_through") or [])
        n = int(args.get("n", 50))

        rows = []
        for entry in ctx.pool.entries:
            if outcome == "success" and entry.success is not True:
                continue
            if outcome == "failure" and entry.success is not False:
                continue
            if passes_through:
                cp = entry.cluster_path or []
                if not _is_subsequence(passes_through, cp):
                    continue
            rows.append({
                "rollout_id": entry.rollout_id,
                "outcome": (
                    "success" if entry.success is True
                    else "failure" if entry.success is False else "unknown"
                ),
                "cluster_path_ids": entry.cluster_path,
                "length": entry.length,
            })
        return ToolResult.text(
            "list_rollouts",
            json.dumps({"n_rollouts": len(rows), "rollouts": rows[:n]}, default=str),
        )

    return ToolSpec(
        name="list_rollouts",
        description=(
            "Filter the rollout pool by outcome and/or required cluster traversal. "
            "passes_through is an in-order subsequence of node ids the rollout must hit."
        ),
        input_schema=S.LIST_ROLLOUTS,
        func=_run,
        cost="cheap",
        # Filtered rollout lookup. Charges normally; remains callable after
        # exhaustion so the agent can locate a reference_rollout_id that
        # passes through a chosen target_cluster.
        bypass_when_exhausted=True,
    )


def _is_subsequence(needle: List[int], haystack: List[int]) -> bool:
    """In-order (not contiguous) subsequence check."""
    it = iter(haystack or [])
    return all(any(x == n for x in it) for n in needle)


# ---------------------------------------------------------------------------
# get_slice_video
# ---------------------------------------------------------------------------


def _make_get_slice_video(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        sid = str(args.get("slice_id", ""))
        fmt = str(args.get("format", "storyboard"))
        parsed = parse_slice_id(sid)
        if parsed is None:
            return ToolResult.error(
                "get_slice_video",
                f"unparseable slice_id {sid!r} (expected 'r0001_t12_t30')",
                code="bad_arg",
            )
        rid, start, end = parsed
        try:
            entry = ctx.pool.by_id(rid)
        except KeyError:
            return ToolResult.error(
                "get_slice_video",
                f"rollout_id={rid!r} not in pool",
                code="not_found",
            )

        sb_kwargs = _storyboard_kwargs(ctx)
        mode = _storyboard_mode(ctx)
        want_state_text = _include_state_text(ctx)

        # Render visual content.
        if mode == "frames":
            frames = _render_slice_frames(entry.episode_pkl, start, end, **sb_kwargs)
            visual_blocks: List = []
            if frames:
                for fi, frame_img in enumerate(frames):
                    visual_blocks.append(ImageBlock(image=frame_img, caption=f"{sid} frame {fi+1}/{len(frames)}"))
        else:
            composite = _render_slice_storyboard(entry.episode_pkl, start, end, **sb_kwargs)
            visual_blocks = [ImageBlock(image=composite, caption=f"slice {sid}")] if composite else []

        if not visual_blocks:
            return ToolResult.error(
                "get_slice_video",
                f"no frames available for {sid!r} (low-dim run? video format unsupported)",
                code="no_frames",
            )

        # Track inspection.
        ctx.inspected_slices.add(sid)
        if ctx.cluster_labels is not None and ctx.cluster_metadata is not None:
            for i, meta in enumerate(ctx.cluster_metadata):
                if (
                    int(meta.get("rollout_idx", -1)) == rollout_id_to_episode_idx(rid)
                    and _slice_bounds(meta) == (start, end)
                ):
                    label = int(ctx.cluster_labels[i])
                    if label >= 0:
                        ctx.inspected_nodes.add(label)
                    break

        note = " [video format not yet supported on slices; returning storyboard]" if fmt == "video" else ""
        content: List = [TextBlock(text=f"slice {sid} (frames {start}-{end}){note}")]
        content.extend(visual_blocks)

        # Per-frame numeric state/action text (opt-in via storyboard config).
        if want_state_text:
            # Reconstruct the sampled frame indices to align text with images.
            n_frames = sb_kwargs.get("n_frames", 5)
            pad_before = sb_kwargs.get("pad_before", 12)
            pad_after = sb_kwargs.get("pad_after", 12)
            try:
                import pandas as pd
                df_len = len(pd.read_pickle(str(entry.episode_pkl)))
                win_start = max(0, start - pad_before)
                win_end = min(df_len - 1, end + pad_after)
                span = win_end - win_start + 1
                idxs = (
                    [win_start + int(i * (span - 1) / max(1, n_frames - 1)) for i in range(n_frames)]
                    if span >= n_frames else list(range(win_start, win_end + 1))
                )
                state_text = _load_slice_state_text(entry.episode_pkl, idxs, start)
                if state_text:
                    content.append(TextBlock(text=state_text))
            except Exception:
                pass

        return ToolResult(
            name="get_slice_video",
            ok=True,
            content=content,
            metadata={"slice_id": sid, "format": mode},
        )

    return ToolSpec(
        name="get_slice_video",
        description=(
            "Visual content for one slice. format='storyboard' (default) returns a "
            "4-frame composite. format='video' would return an MP4 if available; "
            "currently falls back to storyboard. COUNTS AGAINST THE VISUAL BUDGET."
        ),
        input_schema=S.GET_SLICE_VIDEO,
        func=_run,
        # Storyboard cost is "visual"; video escalates to "video" but only when format=video.
        # The session loop reads the actual cost from each call's args at dispatch time.
        cost="visual",
    )


# ---------------------------------------------------------------------------
# get_rollout_video
# ---------------------------------------------------------------------------


def _make_get_rollout_video(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        rid = str(args.get("rollout_id", ""))
        fmt = str(args.get("format", "storyboard"))
        try:
            entry = ctx.pool.by_id(rid)
        except KeyError:
            return ToolResult.error(
                "get_rollout_video",
                f"rollout_id={rid!r} not in pool",
                code="not_found",
            )

        if fmt == "storyboard":
            img = _load_storyboard(entry.storyboard_path)
            if img is None:
                # Fall back to rendering on the fly from the pkl.
                img = _render_slice_storyboard(
                    entry.episode_pkl, 0, max(entry.length - 1, 0),
                    **_storyboard_kwargs(ctx),
                )
            if img is None:
                return ToolResult.error(
                    "get_rollout_video",
                    f"no storyboard available for {rid!r}",
                    code="no_frames",
                )
            ctx.inspected_rollouts.add(rid)
            return ToolResult(
                name="get_rollout_video",
                ok=True,
                content=[
                    TextBlock(text=f"rollout {rid} storyboard"),
                    ImageBlock(image=img, caption=f"rollout {rid} storyboard"),
                ],
                metadata={"rollout_id": rid, "format": "storyboard"},
            )
        # format == 'video'
        if entry.video_path is None or not entry.video_path.exists():
            return ToolResult.error(
                "get_rollout_video",
                f"no video available for {rid!r}",
                code="no_video",
            )
        ctx.inspected_rollouts.add(rid)
        return ToolResult(
            name="get_rollout_video",
            ok=True,
            content=[
                TextBlock(text=f"rollout {rid} video at {entry.video_path}"),
            ],
            metadata={"rollout_id": rid, "format": "video", "video_path": str(entry.video_path)},
        )

    return ToolSpec(
        name="get_rollout_video",
        description=(
            "Visual content for one rollout. format='storyboard' (cheap; returns 4-frame "
            "composite) or format='video' (path to MP4). Both COUNT AGAINST THE BUDGET; "
            "video also against the smaller video budget."
        ),
        input_schema=S.GET_ROLLOUT_VIDEO,
        func=_run,
        cost="visual",
    )


# ---------------------------------------------------------------------------
# Frame loaders
# ---------------------------------------------------------------------------


def _load_storyboard(path: Optional[Path]) -> Optional[Image.Image]:
    if path is None or not path.exists():
        return None
    try:
        return Image.open(path).convert("RGB")
    except Exception:
        return None


def _storyboard_kwargs(ctx: SessionContext) -> Dict[str, Any]:
    """Extract storyboard-render kwargs from ``ctx.config['storyboard']``."""
    cfg = (ctx.config or {}).get("storyboard") or {}
    kw: Dict[str, Any] = {}
    if "n_frames" in cfg:
        kw["n_frames"] = int(cfg["n_frames"])
    if "pad_before" in cfg:
        kw["pad_before"] = int(cfg["pad_before"])
    if "pad_after" in cfg:
        kw["pad_after"] = int(cfg["pad_after"])
    if cfg.get("cameras"):
        kw["cameras"] = tuple(cfg["cameras"])
    if cfg.get("target_size"):
        ts = cfg["target_size"]
        kw["target_size"] = (int(ts[0]), int(ts[1]))
    return kw


def _storyboard_mode(ctx: SessionContext) -> str:
    cfg = (ctx.config or {}).get("storyboard") or {}
    return str(cfg.get("mode", "composite"))


def _include_state_text(ctx: SessionContext) -> bool:
    cfg = (ctx.config or {}).get("storyboard") or {}
    return bool(cfg.get("include_state_text", False))


# Default camera preference order, used when the caller does not specify cameras.
# A scene-level view first (so the agent can localize the action), then a wrist
# camera if the task records one (so grasp alignment is legible).
_DEFAULT_CAMERA_PREFERENCE: Tuple[str, ...] = (
    "img_agentview",
    "img_robot0_eye_in_hand",
    "img",
    "img_shouldercamera0",
    "img_shouldercamera1",
    "img_robot1_eye_in_hand",
    "frame",
    "image",
)


def _resolve_cameras(
    df_columns: List[str],
    requested: Optional[Tuple[str, ...]],
) -> List[str]:
    """Pick the camera columns to render.

    If *requested* is given, return the subset that actually exists in
    *df_columns*, preserving the requested order. Otherwise auto-select a
    sensible default: a scene-level view (so the agent can localize the
    action), plus every wrist camera that exists (so grasp alignment is
    legible regardless of which arm is doing the work). Falls back to the
    first available preference column when no scene view is present.
    """
    if requested:
        return [c for c in requested if c in df_columns]

    cols = set(df_columns)
    out: List[str] = []
    for scene in ("img_agentview", "img", "frame", "image"):
        if scene in cols:
            out.append(scene)
            break
    for wrist in ("img_robot0_eye_in_hand", "img_robot1_eye_in_hand"):
        if wrist in cols:
            out.append(wrist)
    if not out:
        out = [c for c in _DEFAULT_CAMERA_PREFERENCE if c in cols][:1]
    return out


def _render_slice_storyboard(
    pkl_path: Path,
    start: int,
    end: int,
    *,
    n_frames: int = 5,
    pad_before: int = 12,
    pad_after: int = 12,
    cameras: Optional[Tuple[str, ...]] = None,
    target_size: Tuple[int, int] = (1024, 1024),
) -> Optional[Image.Image]:
    """Render a multi-camera, time-padded storyboard for slice ``[start, end]``.

    Layout: ``len(cameras)`` rows × ``n_frames`` columns. Each panel is one
    camera's view at one sampled timestep. Time runs left-to-right. The
    sampling window is ``[start - pad_before, end + pad_after]`` clamped to
    the rollout's valid frame range, so the agent can see what happens
    *around* a short slice rather than a near-static snapshot.

    Returns ``None`` for low-dimensional runs (no image columns in the pkl).
    """
    try:
        import pandas as pd  # local import so tools/__init__ stays lightweight

        df = pd.read_pickle(str(pkl_path))
    except Exception:
        return None

    cols = _resolve_cameras(list(df.columns), cameras)
    if not cols:
        return None

    n_steps = len(df)
    if n_steps == 0:
        return None

    win_start = max(0, start - max(0, pad_before))
    win_end = min(n_steps - 1, end + max(0, pad_after))
    if win_end < win_start:
        return None
    span = win_end - win_start + 1

    n_frames = max(1, int(n_frames))
    if span >= n_frames:
        idxs = [
            win_start + int(i * (span - 1) / max(1, n_frames - 1))
            for i in range(n_frames)
        ]
    else:
        idxs = list(range(win_start, win_end + 1))
    n_actual = len(idxs)

    rows: List[Image.Image] = []
    for col in cols:
        arrs = df[col].to_list()
        if not arrs:
            continue
        rows.append(
            [Image.fromarray(np.asarray(arrs[i]).astype("uint8")) for i in idxs]
        )
    if not rows:
        return None

    # Build a (n_cameras × n_frames) grid: rows = cameras, cols = frames.
    cell_w = target_size[0] // n_actual
    cell_h = target_size[1] // len(rows)
    canvas = Image.new("RGB", target_size, (0, 0, 0))
    for r, frames in enumerate(rows):
        for c, frame in enumerate(frames):
            thumb = frame.convert("RGB").resize((cell_w, cell_h), Image.LANCZOS)
            canvas.paste(thumb, (c * cell_w, r * cell_h))
    return canvas


def _render_slice_frames(
    pkl_path: Path,
    start: int,
    end: int,
    *,
    n_frames: int = 5,
    pad_before: int = 12,
    pad_after: int = 12,
    cameras: Optional[Tuple[str, ...]] = None,
    target_size: Tuple[int, int] = (1024, 1024),
) -> Optional[List[Image.Image]]:
    """Return one image per sampled timestep with all cameras stacked vertically.

    Same frame selection logic as ``_render_slice_storyboard`` but returns a
    list instead of a grid, preserving per-frame resolution. Each returned
    image is ``(target_size[0], target_size[1])`` with camera rows stacked.
    """
    try:
        import pandas as pd
        df = pd.read_pickle(str(pkl_path))
    except Exception:
        return None

    cols = _resolve_cameras(list(df.columns), cameras)
    if not cols:
        return None

    n_steps = len(df)
    if n_steps == 0:
        return None

    win_start = max(0, start - max(0, pad_before))
    win_end = min(n_steps - 1, end + max(0, pad_after))
    if win_end < win_start:
        return None
    span = win_end - win_start + 1
    n_frames = max(1, int(n_frames))
    idxs = (
        [win_start + int(i * (span - 1) / max(1, n_frames - 1)) for i in range(n_frames)]
        if span >= n_frames
        else list(range(win_start, win_end + 1))
    )

    arrs_by_col = {}
    for col in cols:
        arrs_by_col[col] = df[col].to_list()

    cell_h = target_size[1] // len(cols)
    cell_w = target_size[0]
    out: List[Image.Image] = []
    for tidx in idxs:
        canvas = Image.new("RGB", (cell_w, cell_h * len(cols)), (0, 0, 0))
        for r, col in enumerate(cols):
            arr = arrs_by_col[col]
            if tidx < len(arr):
                thumb = Image.fromarray(np.asarray(arr[tidx]).astype("uint8"))
                thumb = thumb.convert("RGB").resize((cell_w, cell_h), Image.LANCZOS)
                canvas.paste(thumb, (0, r * cell_h))
        out.append(canvas)
    return out or None


def _load_slice_state_text(
    pkl_path: Path,
    sampled_idxs: List[int],
    absolute_start: int,
    *,
    max_obs_dim: int = 24,
    max_action_dim: int = 14,
) -> Optional[str]:
    """Format per-timestep obs tail + action for the sampled frame indices.

    Returns a compact text block showing the numeric state the policy received
    and the action it executed at each displayed frame. ``max_obs_dim`` keeps
    the obs vector bounded (last N dims — typically proprioception + gripper).
    ``max_action_dim`` keeps action bounded (Franka = 7 joints + 1 gripper
    per arm = 14 for dual-arm transport_mh).
    """
    try:
        import pandas as pd
        df = pd.read_pickle(str(pkl_path))
    except Exception:
        return None

    if "obs" not in df.columns and "action" not in df.columns:
        return None

    lines = ["Numeric state at each displayed frame (obs tail + action):"]
    for local_t, tidx in enumerate(sampled_idxs):
        if tidx >= len(df):
            continue
        row = df.iloc[tidx]
        parts = [f"t={tidx}(abs)"]
        if "obs" in row.index:
            obs = np.asarray(row["obs"]).reshape(-1)
            tail = obs[-max_obs_dim:] if obs.size > max_obs_dim else obs
            parts.append("obs_tail=[" + ", ".join(f"{v:.3f}" for v in tail.tolist()) + "]")
        if "action" in row.index:
            act = np.asarray(row["action"]).reshape(-1)
            if max_action_dim and act.size > max_action_dim:
                act = act[:max_action_dim]
            parts.append("action=[" + ", ".join(f"{v:.3f}" for v in act.tolist()) + "]")
        lines.append("  " + "  ".join(parts))
    return "\n".join(lines) if len(lines) > 1 else None


# ---------------------------------------------------------------------------
# Module-level factory
# ---------------------------------------------------------------------------


def build(ctx: SessionContext) -> List[ToolSpec]:
    """Build all Layer 2 tool specs for the graph-aware (A_G) condition."""
    return [
        _make_list_slices_in_node(ctx),
        _make_get_rollout_summary(ctx),
        _make_list_rollouts(ctx),
        _make_get_slice_video(ctx),
        _make_get_rollout_video(ctx),
    ]
