"""Layer 2 — slice and rollout access tools.

Surfaces the underlying rollouts and slices behind the graph. Tools split into
two cost classes:

* **Cheap (textual)**: ``list_slices_in_node``, ``get_rollout_summary``,
  ``list_rollouts``. Return only structured data.
* **Visual / video**: ``get_slice_video``, ``get_rollout_video``. Return
  PIL images (storyboard) or paths to MP4s (video). Counted against the
  budget; cached so a re-fetched slice charges nothing on the second call.

Slice IDs follow the form ``"{rollout_id}_t{start_frame}_t{end_frame}"``,
e.g. ``"r0023_t12_t30"``. The id is generated by the ``list_slices_in_node``
response and parsed by the ``get_slice_*`` tools.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from PIL import Image

from policy_doctor.vlm.proposals.agents.context import SessionContext
from policy_doctor.vlm.proposals.agents.tools import schema as S
from policy_doctor.vlm.proposals.agents.tools.types import (
    ImageBlock,
    TextBlock,
    ToolResult,
    ToolSpec,
)
from policy_doctor.vlm.proposals.pool import (
    episode_idx_to_rollout_id,
    rollout_id_to_episode_idx,
)


_SLICE_ID_RE = re.compile(r"^(r\d+)_t(\d+)_t(\d+)$")


# ---------------------------------------------------------------------------
# Slice id helpers
# ---------------------------------------------------------------------------


def slice_id(rollout_id: str, start: int, end: int) -> str:
    return f"{rollout_id}_t{int(start)}_t{int(end)}"


def parse_slice_id(slice_id_str: str) -> Optional[Tuple[str, int, int]]:
    m = _SLICE_ID_RE.match(slice_id_str.strip())
    if not m:
        return None
    return m.group(1), int(m.group(2)), int(m.group(3))


def _slice_bounds(meta: Dict[str, Any]) -> Tuple[int, int]:
    start = int(meta.get("window_start", meta.get("timestep", 0)))
    end = meta.get("window_end")
    if end is None:
        end = start + int(meta.get("window_width", 1)) - 1
    else:
        end = int(end) - 1
    return start, end


# ---------------------------------------------------------------------------
# list_slices_in_node
# ---------------------------------------------------------------------------


def _make_list_slices_in_node(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        node_id = int(args.get("node_id"))
        n = int(args.get("n", 20))
        sort_by = str(args.get("sort_by", "centroid_distance"))
        if node_id >= 0:
            ctx.inspected_nodes.add(int(node_id))

        if ctx.cluster_labels is None or ctx.cluster_metadata is None:
            return ToolResult.error(
                "list_slices_in_node",
                "no cluster_labels/metadata available on session context",
                code="not_available",
            )

        labels = np.asarray(ctx.cluster_labels)
        members = [
            (i, ctx.cluster_metadata[i])
            for i in range(len(labels))
            if int(labels[i]) == node_id
        ]
        if not members:
            return ToolResult.text(
                "list_slices_in_node",
                json.dumps({"node_id": node_id, "n_slices": 0, "slices": []}),
            )

        # Outcome and rollout-id annotations from metadata.
        outcomes = {True: "success", False: "failure", None: "unknown"}
        rows: List[Dict[str, Any]] = []
        for slice_idx, meta in members:
            ep_idx = int(meta.get("rollout_idx", meta.get("demo_idx", -1)))
            if ep_idx < 0:
                continue
            rid = episode_idx_to_rollout_id(ep_idx)
            start, end = _slice_bounds(meta)
            rows.append({
                "slice_idx": slice_idx,
                "slice_id": slice_id(rid, start, end),
                "rollout_id": rid,
                "start_frame": start,
                "end_frame": end,
                "outcome": outcomes.get(meta.get("success")),
                # Centroid distance filled in below if available.
                "centroid_distance": None,
            })

        # Centroid-distance sort if centroids + per-slice embeddings are available.
        if sort_by == "centroid_distance" and ctx.cluster_centroids is not None:
            try:
                _populate_centroid_distance(ctx, rows)
                rows.sort(key=lambda r: (r["centroid_distance"] is None, r["centroid_distance"] or 0.0))
            except Exception:
                # Non-fatal — return unsorted with a note.
                pass
        else:
            # Stable random shuffle seeded by node_id for reproducibility.
            rng = np.random.default_rng(seed=int(node_id))
            indices = list(range(len(rows)))
            rng.shuffle(indices)
            rows = [rows[i] for i in indices]

        return ToolResult.text(
            "list_slices_in_node",
            json.dumps(
                {"node_id": node_id, "n_slices": len(rows), "slices": rows[:n]},
                default=str,
            ),
        )

    return ToolSpec(
        name="list_slices_in_node",
        description=(
            "List slices assigned to a behavior cluster, with rollout id, frame range, "
            "and outcome. Use sort_by='centroid_distance' (default) for the most "
            "prototypical examples first."
        ),
        input_schema=S.LIST_SLICES_IN_NODE,
        func=_run,
        cost="cheap",
        # Specific cluster lookup. Charges normally; remains callable after
        # exhaustion as a recovery affordance for the cluster_not_inspected gate.
        bypass_when_exhausted=True,
    )


def _populate_centroid_distance(ctx: SessionContext, rows: List[Dict[str, Any]]) -> None:
    """Fill ``centroid_distance`` for each row, when per-slice coords are stashed in metadata.

    Most clustering pipelines record post-UMAP coordinates in ``metadata[i]['coords']``
    or ``metadata[i]['embedding']``. We try a few common keys and fall back to
    leaving the distance as None when none are present.
    """
    centroids = np.asarray(ctx.cluster_centroids)
    for row in rows:
        meta = ctx.cluster_metadata[row["slice_idx"]]
        coords = meta.get("coords") or meta.get("embedding") or meta.get("reduced_coords")
        if coords is None:
            continue
        c = np.asarray(coords, dtype=float)
        # Distance to *this* row's assigned cluster centroid.
        labels = np.asarray(ctx.cluster_labels)
        node_id = int(labels[row["slice_idx"]])
        if 0 <= node_id < len(centroids):
            d = float(np.linalg.norm(c - centroids[node_id]))
            row["centroid_distance"] = round(d, 4)


# ---------------------------------------------------------------------------
# get_rollout_summary  (graph-aware variant; A_NG version is in no_graph.py)
# ---------------------------------------------------------------------------


def _make_get_rollout_summary(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        rid = str(args.get("rollout_id", ""))
        try:
            entry = ctx.pool.by_id(rid)
        except KeyError:
            return ToolResult.error(
                "get_rollout_summary",
                f"rollout_id={rid!r} not in pool",
                code="not_found",
            )

        outcome = (
            "success" if entry.success is True
            else ("failure" if entry.success is False else "unknown")
        )
        cluster_path_named = None
        if entry.cluster_path:
            from policy_doctor.vlm.proposals.agents.tools.topology import _node_name

            cluster_path_named = [_node_name(c) for c in entry.cluster_path]

        payload = {
            "rollout_id": entry.rollout_id,
            "outcome": outcome,
            "length": entry.length,
            "cluster_path_ids": entry.cluster_path,
            "cluster_path": cluster_path_named,
            "has_storyboard": entry.storyboard_path is not None and entry.storyboard_path.exists(),
            "has_video": entry.video_path is not None and entry.video_path.exists(),
        }
        return ToolResult.text("get_rollout_summary", json.dumps(payload, default=str))

    return ToolSpec(
        name="get_rollout_summary",
        description=(
            "Cluster path and metadata for one rollout (no images). The cluster_path "
            "is the run-length-collapsed sequence of behavior cluster ids the rollout "
            "traversed, ending in SUCCESS / FAILURE / END."
        ),
        input_schema=S.GET_ROLLOUT_SUMMARY,
        func=_run,
        cost="cheap",
        # Specific rollout lookup. Charges normally; remains callable after
        # exhaustion so the agent can verify reference_rollout_id pre-submit.
        bypass_when_exhausted=True,
    )


# ---------------------------------------------------------------------------
# list_rollouts
# ---------------------------------------------------------------------------


def _make_list_rollouts(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        outcome = args.get("outcome")
        passes_through = list(args.get("passes_through") or [])
        n = int(args.get("n", 50))

        rows = []
        for entry in ctx.pool.entries:
            if outcome == "success" and entry.success is not True:
                continue
            if outcome == "failure" and entry.success is not False:
                continue
            if passes_through:
                cp = entry.cluster_path or []
                if not _is_subsequence(passes_through, cp):
                    continue
            rows.append({
                "rollout_id": entry.rollout_id,
                "outcome": (
                    "success" if entry.success is True
                    else "failure" if entry.success is False else "unknown"
                ),
                "cluster_path_ids": entry.cluster_path,
                "length": entry.length,
            })
        return ToolResult.text(
            "list_rollouts",
            json.dumps({"n_rollouts": len(rows), "rollouts": rows[:n]}, default=str),
        )

    return ToolSpec(
        name="list_rollouts",
        description=(
            "Filter the rollout pool by outcome and/or required cluster traversal. "
            "passes_through is an in-order subsequence of node ids the rollout must hit."
        ),
        input_schema=S.LIST_ROLLOUTS,
        func=_run,
        cost="cheap",
        # Filtered rollout lookup. Charges normally; remains callable after
        # exhaustion so the agent can locate a reference_rollout_id that
        # passes through a chosen target_cluster.
        bypass_when_exhausted=True,
    )


def _is_subsequence(needle: List[int], haystack: List[int]) -> bool:
    """In-order (not contiguous) subsequence check."""
    it = iter(haystack or [])
    return all(any(x == n for x in it) for n in needle)


# ---------------------------------------------------------------------------
# get_slice_video
# ---------------------------------------------------------------------------


def _make_get_slice_video(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        sid = str(args.get("slice_id", ""))
        fmt = str(args.get("format", "storyboard"))
        parsed = parse_slice_id(sid)
        if parsed is None:
            return ToolResult.error(
                "get_slice_video",
                f"unparseable slice_id {sid!r} (expected 'r0001_t12_t30')",
                code="bad_arg",
            )
        rid, start, end = parsed
        try:
            entry = ctx.pool.by_id(rid)
        except KeyError:
            return ToolResult.error(
                "get_slice_video",
                f"rollout_id={rid!r} not in pool",
                code="not_found",
            )

        composite = _render_slice_storyboard(entry.episode_pkl, start, end)
        if composite is None:
            return ToolResult.error(
                "get_slice_video",
                f"no frames available for {sid!r} (low-dim run? video format unsupported)",
                code="no_frames",
            )

        # Track inspection: a slice video counts as inspecting the cluster
        # the slice belongs to.
        ctx.inspected_slices.add(sid)
        if ctx.cluster_labels is not None and ctx.cluster_metadata is not None:
            for i, meta in enumerate(ctx.cluster_metadata):
                if (
                    int(meta.get("rollout_idx", -1)) == rollout_id_to_episode_idx(rid)
                    and _slice_bounds(meta) == (start, end)
                ):
                    label = int(ctx.cluster_labels[i])
                    if label >= 0:
                        ctx.inspected_nodes.add(label)
                    break

        caption = f"slice {sid} (frames {start}-{end})"
        # Only storyboard format supported in v1; agent asking for 'video' gets storyboard with a note.
        note = ""
        if fmt == "video":
            note = " [video format not yet supported on slices; returning storyboard]"
        return ToolResult(
            name="get_slice_video",
            ok=True,
            content=[
                TextBlock(text=caption + note),
                ImageBlock(image=composite, caption=caption),
            ],
            metadata={"slice_id": sid, "format": "storyboard"},
        )

    return ToolSpec(
        name="get_slice_video",
        description=(
            "Visual content for one slice. format='storyboard' (default) returns a "
            "4-frame composite. format='video' would return an MP4 if available; "
            "currently falls back to storyboard. COUNTS AGAINST THE VISUAL BUDGET."
        ),
        input_schema=S.GET_SLICE_VIDEO,
        func=_run,
        # Storyboard cost is "visual"; video escalates to "video" but only when format=video.
        # The session loop reads the actual cost from each call's args at dispatch time.
        cost="visual",
    )


# ---------------------------------------------------------------------------
# get_rollout_video
# ---------------------------------------------------------------------------


def _make_get_rollout_video(ctx: SessionContext) -> ToolSpec:
    def _run(args: Dict[str, Any]) -> ToolResult:
        rid = str(args.get("rollout_id", ""))
        fmt = str(args.get("format", "storyboard"))
        try:
            entry = ctx.pool.by_id(rid)
        except KeyError:
            return ToolResult.error(
                "get_rollout_video",
                f"rollout_id={rid!r} not in pool",
                code="not_found",
            )

        if fmt == "storyboard":
            img = _load_storyboard(entry.storyboard_path)
            if img is None:
                # Fall back to rendering on the fly from the pkl.
                img = _render_slice_storyboard(entry.episode_pkl, 0, max(entry.length - 1, 0))
            if img is None:
                return ToolResult.error(
                    "get_rollout_video",
                    f"no storyboard available for {rid!r}",
                    code="no_frames",
                )
            ctx.inspected_rollouts.add(rid)
            return ToolResult(
                name="get_rollout_video",
                ok=True,
                content=[
                    TextBlock(text=f"rollout {rid} storyboard"),
                    ImageBlock(image=img, caption=f"rollout {rid} storyboard"),
                ],
                metadata={"rollout_id": rid, "format": "storyboard"},
            )
        # format == 'video'
        if entry.video_path is None or not entry.video_path.exists():
            return ToolResult.error(
                "get_rollout_video",
                f"no video available for {rid!r}",
                code="no_video",
            )
        ctx.inspected_rollouts.add(rid)
        return ToolResult(
            name="get_rollout_video",
            ok=True,
            content=[
                TextBlock(text=f"rollout {rid} video at {entry.video_path}"),
            ],
            metadata={"rollout_id": rid, "format": "video", "video_path": str(entry.video_path)},
        )

    return ToolSpec(
        name="get_rollout_video",
        description=(
            "Visual content for one rollout. format='storyboard' (cheap; returns 4-frame "
            "composite) or format='video' (path to MP4). Both COUNT AGAINST THE BUDGET; "
            "video also against the smaller video budget."
        ),
        input_schema=S.GET_ROLLOUT_VIDEO,
        func=_run,
        cost="visual",
    )


# ---------------------------------------------------------------------------
# Frame loaders
# ---------------------------------------------------------------------------


def _load_storyboard(path: Optional[Path]) -> Optional[Image.Image]:
    if path is None or not path.exists():
        return None
    try:
        return Image.open(path).convert("RGB")
    except Exception:
        return None


def _render_slice_storyboard(
    pkl_path: Path, start: int, end: int, *, n_frames: int = 4
) -> Optional[Image.Image]:
    """Render a 4-frame storyboard cropped to ``[start, end]``.

    Returns ``None`` for low-dimensional runs (no per-step image columns in
    the pkl). Mirrors the loader in ``build_rollout_pool`` so cropping
    behavior matches the full-rollout storyboards.
    """
    try:
        import pandas as pd  # local import so tools/__init__ stays lightweight

        df = pd.read_pickle(str(pkl_path))
    except Exception:
        return None

    # Try common image-column names produced by eval_save_episodes / robomimic.
    # Order: simple "frame" / "image" first; then the multi-camera robocasa-style
    # keys ("img", "img_agentview", etc.).
    image_col_candidates = (
        "frame", "image",
        "img", "img_agentview", "img_shouldercamera0", "img_shouldercamera1",
        "img_robot0_eye_in_hand", "img_robot1_eye_in_hand",
    )
    col = next((c for c in image_col_candidates if c in df.columns), None)
    if col is None:
        return None
    arrs = df[col].to_list()
    if not arrs:
        return None

    end = min(end, len(arrs) - 1)
    start = max(start, 0)
    if end < start:
        return None

    span = end - start + 1
    if span >= n_frames:
        idxs = [start + int(i * (span - 1) / max(1, n_frames - 1)) for i in range(n_frames)]
    else:
        idxs = list(range(start, end + 1))

    from policy_doctor.vlm.storyboard import make_storyboard

    frames = [Image.fromarray(np.asarray(arrs[i]).astype("uint8")) for i in idxs]
    return make_storyboard(frames)


# ---------------------------------------------------------------------------
# Module-level factory
# ---------------------------------------------------------------------------


def build(ctx: SessionContext) -> List[ToolSpec]:
    """Build all Layer 2 tool specs for the graph-aware (A_G) condition."""
    return [
        _make_list_slices_in_node(ctx),
        _make_get_rollout_summary(ctx),
        _make_list_rollouts(ctx),
        _make_get_slice_video(ctx),
        _make_get_rollout_video(ctx),
    ]
