"""Streamlit tab: MimicGen EEF trajectory distribution.

Visualises the end-effector trajectories from a
:class:`~policy_doctor.curation_pipeline.steps.generate_mimicgen_demos.GenerateMimicgenDemosStep`
result, answering the question:

    *"Given a fixed seed demonstration, are the demonstrations generated by
    MimicGen within the seed's initial state-space distribution?"*

The tab can load data in two ways:
1. **From a pipeline step result dir** — paste the ``generate_mimicgen_demos/``
   step directory; the tab reads ``result.json`` directly.
2. **From HDF5 files** — provide paths to the prepared seed HDF5 and the
   generated ``demo.hdf5``; the tab extracts EEF trajectories on the fly.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import streamlit as st

from policy_doctor.plotting.plotly.eef_trajectories import (
    create_eef_trajectory_figure,
    create_initial_eef_scatter_2d,
)


def _load_result_json(step_dir: Path) -> dict[str, Any] | None:
    result_path = step_dir / "result.json"
    if not result_path.exists():
        return None
    with open(result_path) as f:
        return json.load(f)


def _xyz_from_result(result: dict, key: str) -> list[np.ndarray]:
    raw = result.get(key, [])
    if not raw:
        return []
    # seed_eef_xyz is a list of (T, 3) lists; generated_eef_xyz is list of list of (T, 3)
    # Both stored as nested python lists
    if isinstance(raw[0][0], list):
        # list of trajectories, each trajectory is list of [x,y,z]
        return [np.array(t, dtype=np.float32) for t in raw]
    else:
        # single trajectory wrapped in a list
        return [np.array(raw, dtype=np.float32)]


def render_tab(config: Any, data: Any, task_config_stem: str = "") -> None:
    """Render the MimicGen EEF tab."""
    st.header("MimicGen EEF Trajectory Distribution")
    st.caption(
        "Investigate whether MimicGen-generated demonstrations are within the "
        "seed demonstration's initial state-space distribution."
    )

    # --- Load mode ---
    load_mode = st.radio(
        "Data source",
        ["Pipeline step result dir", "Manual HDF5 paths"],
        horizontal=True,
        key="mg_eef_load_mode",
    )

    seed_eef_list: list[np.ndarray] = []
    generated_eef_list: list[np.ndarray] = []
    stats: dict = {}
    seed_demo_key: str = ""

    if load_mode == "Pipeline step result dir":
        step_dir_str = st.text_input(
            "Path to generate_mimicgen_demos/ step directory",
            placeholder="/path/to/run_dir/generate_mimicgen_demos",
            key="mg_eef_step_dir",
        )
        if step_dir_str:
            step_dir = Path(step_dir_str.strip())
            if not step_dir.is_dir():
                st.error(f"Directory not found: {step_dir}")
            else:
                result = _load_result_json(step_dir)
                if result is None:
                    st.warning("No result.json found. Has the step run yet?")
                else:
                    seed_demo_key = result.get("seed_demo_key", "")
                    stats = result.get("stats", {})
                    seed_raw = result.get("seed_eef_xyz", [])
                    gen_raw = result.get("generated_eef_xyz", [])
                    if seed_raw:
                        seed_eef_list = [np.array(t, dtype=np.float32) for t in seed_raw]
                    if gen_raw:
                        generated_eef_list = [np.array(t, dtype=np.float32) for t in gen_raw]
                    st.success(
                        f"Loaded: seed_demo={seed_demo_key!r}, "
                        f"generated demos={len(generated_eef_list)}"
                    )

    else:  # Manual HDF5 paths
        from policy_doctor.mimicgen.eef import extract_eef_xyz_from_hdf5

        col1, col2 = st.columns(2)
        with col1:
            seed_hdf5_str = st.text_input(
                "Prepared seed HDF5",
                placeholder="/path/to/seed_demo.hdf5",
                key="mg_eef_seed_hdf5",
            )
        with col2:
            gen_hdf5_str = st.text_input(
                "Generated demo.hdf5",
                placeholder="/path/to/demo.hdf5",
                key="mg_eef_gen_hdf5",
            )

        if seed_hdf5_str:
            seed_path = Path(seed_hdf5_str.strip())
            if seed_path.exists():
                try:
                    seed_eef_list = extract_eef_xyz_from_hdf5(seed_path)
                    st.caption(f"Seed: {len(seed_eef_list)} trajectory/ies loaded.")
                except Exception as e:
                    st.error(f"Failed to load seed EEF: {e}")
            else:
                st.warning(f"Seed HDF5 not found: {seed_path}")

        if gen_hdf5_str:
            gen_path = Path(gen_hdf5_str.strip())
            if gen_path.exists():
                try:
                    generated_eef_list = extract_eef_xyz_from_hdf5(gen_path)
                    st.caption(f"Generated: {len(generated_eef_list)} trajectories loaded.")
                except Exception as e:
                    st.error(f"Failed to load generated EEF: {e}")
            else:
                st.warning(f"Generated HDF5 not found: {gen_path}")

    # --- Stats ---
    if stats:
        st.divider()
        st.subheader("Generation stats")
        c1, c2, c3 = st.columns(3)
        c1.metric("Successes", stats.get("num_success", "?"))
        c2.metric("Attempts", stats.get("num_attempts", "?"))
        rate = stats.get("success_rate")
        c3.metric("Success rate", f"{rate:.1f}%" if isinstance(rate, (int, float)) else "?")
        if seed_demo_key:
            st.caption(f"Seed demo: ``{seed_demo_key}``")

    if not seed_eef_list and not generated_eef_list:
        st.info("Load data above to see EEF trajectory visualisations.")
        return

    # --- Display options ---
    st.divider()
    with st.expander("Display options", expanded=False):
        show_mean = st.checkbox("Show mean trajectory", value=True, key="mg_eef_mean")
        gen_opacity = st.slider(
            "Generated trajectory opacity", 0.05, 1.0, 0.2, 0.05, key="mg_eef_opacity"
        )
        max_gen = st.number_input(
            "Max generated trajectories to show (0 = all)",
            min_value=0, max_value=500, value=0, step=10, key="mg_eef_max_gen",
        )

    seed_xyz = seed_eef_list[0] if seed_eef_list else None
    gen_to_show = generated_eef_list
    if max_gen and max_gen > 0:
        gen_to_show = generated_eef_list[:max_gen]

    # --- 3D trajectory figure ---
    st.subheader("3D EEF trajectories")
    st.caption(
        f"Seed (red): 1 demo  |  Generated (blue): {len(gen_to_show)} demos"
        + (f" (of {len(generated_eef_list)} total)" if max_gen and max_gen < len(generated_eef_list) else "")
    )
    fig_3d = create_eef_trajectory_figure(
        seed_xyz=seed_xyz,
        generated_xyz_list=gen_to_show,
        show_mean=show_mean,
        generated_opacity=gen_opacity,
    )
    st.plotly_chart(fig_3d, use_container_width=True)

    # --- 2D initial position scatter ---
    st.subheader("Initial positions (t=0) — XY plane")
    st.caption(
        "The key question: do generated demos start near the seed demo's "
        "initial end-effector position?"
    )
    fig_2d = create_initial_eef_scatter_2d(
        seed_xyz=seed_xyz,
        generated_xyz_list=gen_to_show,
    )
    st.plotly_chart(fig_2d, use_container_width=True)

    # --- Summary statistics ---
    if generated_eef_list and seed_xyz is not None:
        t0_gen = np.stack([t[0] for t in generated_eef_list if t.shape[0] > 0])
        t0_seed = seed_xyz[0]
        dists = np.linalg.norm(t0_gen - t0_seed, axis=1)
        st.divider()
        st.subheader("Initial position statistics")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Mean dist to seed", f"{dists.mean():.4f} m")
        c2.metric("Max dist to seed", f"{dists.max():.4f} m")
        c3.metric("Min dist to seed", f"{dists.min():.4f} m")
        c4.metric("Std dist to seed", f"{dists.std():.4f} m")
